# Generated by Django 3.0.6 on 2020-05-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.TextField(max_length=50)),
                ('profileImage', models.FileField(blank=True, null=True, upload_to='profileImages/')),
            ],
        ),
    ]
